apiVersion: v1
kind: Secret
metadata:
  name: gearbox-middleware-jwt-keys-g3auto
type: Opaque
data:
    jwt_private_key.pem: {{ include "getOrCreateRSAPrivateKey" . }}

---

apiVersion: v1
kind: Secret
metadata:
  name: gearbox-middleware-g3auto
type: Opaque
stringData:
  gearbox-middleware.env: | 
    DEBUG=True
    FORCE_ISSUER=True
    USER_API="http://fence-service/"
    ALLOWED_ISSUERS="http://fence-service/,https://localhost/user"