apiVersion: v1
kind: Service
metadata:
  name: gearbox-middleware-service
  labels:
    {{- include "gearbox-middleware.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gearbox-middleware.selectorLabels" . | nindent 4 }}