global:
  dev: true
  hostname: localhost
  portalApp: pcdc
  dictionaryUrl: https://pcdc-dev-dictionaries.s3.amazonaws.com/pcdc-schema-dev-20230912.json
fence: 
  FENCE_CONFIG:
    MOCK_GOOGLE_AUTH: true
    OPENID_CONNECT:
      google:
        mock_default_user: 'test@example.com'
  image:
    repository: quay.io/pcdc/fence
    tag: 1.12.2

arborist:
  image: 
    repository: quay.io/pcdc/arborist
    tag: 2023.08

peregrine:
  image:
    repository: quay.io/pcdc/peregrine
    tag: "helm-test"

sheepdog:
  image:
    repository: quay.io/pcdc/sheepdog
    tag: "helm-test"


aws-es-proxy:
#currently turn off in base image
  enabled: true
  image:
    repository: abutaha/aws-es-proxy
    tag: 0.8

# guppy:
#   enabled: true
#   image:
#     repository: quay.io/pcdc/guppy
#     tag: 1.5.0

portal:
  image: 
    repository: quay.io/pcdc/windmill
    tag: 1.19.0
    pullPolicy: Always
  resources:
    requests:
      cpu: 0.2
      memory: 500Mi
  gitops: 
    json: ""

audit:
  # -- (bool) Whether to deploy the audit subchart.
  enabled: false

argo-wrapper:
  # -- (bool) Whether to deploy the argo-wrapper subchart.
  enabled: false

metadata:
  # -- (bool) Whether to deploy the metadata subchart.
  enabled: false

pidgin:
  # -- (bool) Whether to deploy the pidgin subchart.
  enabled: false




# fluentd:
#   image:
#     repository: fluent/fluentd-kubernetes-daemonset
#     tag: v1.15.3-debian-cloudwatch-1.0