apiVersion: v1
kind: Secret
metadata:
  name: gearbox-g3auto
type: Opaque
stringData:
  {{- $randomPass := printf "%s%s" "gateway:" (randAlphaNum 32)  }}
  base64Authz.txt: {{ $randomPass | quote | b64enc }}
  gearbox.env: | 
    DEBUG=0
    FORCE_ISSUER=True
    USER_API="http://fence-service/"
    ALLOWED_ISSUERS="http://fence-service/,https://localhost/user"
    DUMMY_S3=True
    DB_DATABASE={{ ( $.Values.postgres.database | default (printf "%s_%s" $.Chart.Name $.Release.Name)  ) }}
    DB_HOST={{ (printf "%s-%s" $.Release.Name "postgresql" )  }}
    DB_USER={{ ( $.Values.postgres.username | default (printf "%s_%s" $.Chart.Name $.Release.Name) ) }}
    ADMIN_LOGINS={{ $randomPass }}
    ENABLE_PHI=True
