---
apiVersion: batch/v1
kind: Job
metadata:
  name: amanuensis-db-migrate
spec:
  template:
    metadata:
      labels:
        app: gen3job
    spec:
      automountServiceAccountToken: false
      volumes:
        - name: yaml-merge
          configMap:
            name: "amanuensis-yaml-merge"
            optional: true
        - name: config-volume
          secret:
            secretName: "amanuensis-config"
        - name: amanuensis-volume
          secret:
            secretName: "amanuensis-creds"
        - name: tmp-pod
          emptyDir: {}
      containers:
      - name: amanuensis
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: PGHOST
            valueFrom:
              secretKeyRef:
                name: amanuensis-dbcreds
                key: host
                optional: false
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: amanuensis-dbcreds
                key: username
                optional: false
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: amanuensis-dbcreds
                key: password
                optional: false
          - name: PGDB
            valueFrom:
              secretKeyRef:
                name: amanuensis-dbcreds
                key: database
                optional: false
          - name: DBREADY
            valueFrom:
              secretKeyRef:
                name: amanuensis-dbcreds
                key: dbcreated
                optional: false
          - name: DB
            value: postgresql://$(PGUSER):$(PGPASSWORD)@$(PGHOST):5432/$(PGDB)
          - name: AMANUENSIS_DB
            value: postgresql://$(PGUSER):$(PGPASSWORD)@$(PGHOST):5432/$(PGDB)
          - name: PYTHONPATH
            value: /var/www/amanuensis
          - name: AMANUENSIS_PUBLIC_CONFIG
            valueFrom:
              configMapKeyRef:
                name: manifest-amanuensis
                key: amanuensis-config-public.yaml
                optional: true
        volumeMounts:
          - name: "config-volume"
            readOnly: true
            mountPath: "/var/www/amanuensis/amanuensis-config.yaml"
            subPath: amanuensis-config.yaml
          - name: "yaml-merge"
            readOnly: true
            mountPath: "/var/www/amanuensis/yaml_merge.py"
            subPath: yaml_merge.py
          - name: "amanuensis-volume"
            readOnly: true
            mountPath: "/var/www/amanuensis/creds.json"
            subPath: creds.json
          - mountPath: /tmp/pod
            name: tmp-pod
        command: ["/bin/bash"]
        args:
          - "-c"
          - |
            # echo "${AMANUENSIS_PUBLIC_CONFIG:-""}" > "/var/www/amanuensis/amanuensis-config-public.yaml"
            # python /var/www/amanuensis/yaml_merge.py /var/www/amanuensis/amanuensis-config-public.yaml /var/www/amanuensis/amanuensis-config-secret.yaml > /var/www/amanuensis/amanuensis-config.yaml
            cd /amanuensis
            fence-create migrate
            if [[ $? != 0 ]]; then
              echo "WARNING: non zero exit code: $?"
            fi
            touch /tmp/pod/completed
      restartPolicy: OnFailure