{{- if .Values.amanuensisJobs.dbMigrateJob }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: amanuensis-db-migrate
spec:
  template:
    metadata:
      labels:
        app: gen3job
    spec:
      automountServiceAccountToken: false
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      containers:
      - name: amanuensis
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: PYTHONPATH
            value: /var/www/amanuensis
        volumeMounts:
          {{- toYaml .Values.volumeMounts | nindent 10 }}
        command: ["/bin/bash"]
        args:
          - "-c"
          - |
            python /var/www/amanuensis/yaml_merge.py /var/www/amanuensis/amanuensis-config-public.yaml /var/www/amanuensis/amanuensis-config-secret.yaml /var/www/amanuensis/amanuensis-config.yaml
            cd /amanuensis
            fence-create migrate
            if [[ $? != 0 ]]; then
              echo "WARNING: non zero exit code: $?"
              exit 1
            fi
      restartPolicy: OnFailure

{{- end }}