{{- if .Values.amanuensisJobs.clearFilterSetCronjob }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: amanuensis-clear-unused-filter-sets
  labels:
    redeploy-hash: "{{ .Release.Revision }}"
spec:
  schedule: "0 0 1 * *"
  concurrencyPolicy: Forbid
  # This is defualt but do we want to keep long term record of deleted filter sets
  # the original filter-sets will not be deleted unless manually done by the user
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: gen3job
        spec:
          automountServiceAccountToken: false
          volumes:
            {{- toYaml .Values.volumes | nindent 12 }}
          containers:
          - name: amanuensis
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
              - name: PYTHONPATH
                value: /var/www/amanuensis
            volumeMounts:
              {{- toYaml .Values.volumeMounts | nindent 14 }}
            command: ["/bin/bash"]
            args:
              - "-c"
              - |
                python /var/www/amanuensis/yaml_merge.py /var/www/amanuensis/amanuensis-config-public.yaml /var/www/amanuensis/amanuensis-config-secret.yaml /var/www/amanuensis/amanuensis-config.yaml
                cd /amanuensis
                clear-old-filter-sets
                if [[ $? != 0 ]]; then
                  echo "WARNING: non zero exit code: $?"
                  exit 1
                fi
          restartPolicy: Never

{{- end }}