apiVersion: v1
kind: Secret
metadata:
  name: amanuensis-secret
type: Opaque
data:
{{ (.Files.Glob "amanuensis-secret/*").AsSecrets | indent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: amanuensis-google-app-creds-secret
type: Opaque
data:
{{ (.Files.Glob "amanuensis-google-creds/*").AsSecrets | indent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: amanuensis-google-storage-creds-secret
type: Opaque
data:
{{ (.Files.Glob "amanuensis-google-creds/*").AsSecrets | indent 2 }}
