apiVersion: v1
kind: Secret
metadata:
  name: amanuensis-creds
type: Opaque
stringData:
  creds.json: |-
      {
        "db_host": "{{ include "gen3.service-postgres" (dict "key" "host" "service" $.Chart.Name "context" $) }}",
        "db_username": "{{include "gen3.service-postgres" (dict "key" "username" "service" $.Chart.Name "context" $) }}",
        "db_password": "{{include "gen3.service-postgres" (dict "key" "password" "service" $.Chart.Name "context" $) }}",
        "db_database": "{{ include "gen3.service-postgres" (dict "key" "database" "service" $.Chart.Name "context" $)}}",
        "hostname": "{{ .Values.global.hostname }}",
        "indexd_password": "",
        "data_delivery_bucket": {{ .Values.AMANUENSIS_CONFIG.DATA_DOWNLOAD_BUCKET }},
        "data_delivery_bucket_aws_key_id": {{ .Values.AMANUENSIS_CONFIG.AWS_CREDENTIALS.aws_access_key_id }},
        "data_delivery_bucket_aws_access_key": {{ .Values.AMANUENSIS_CONFIG.AWS_CREDENTIALS.aws_secret_access_key }}
      }
