apiVersion: v1
kind: Secret
metadata:
  name: amanuensis-config
stringData:
  amanuensis-config.yaml: |
    BASE_URL: https://{{ .Values.global.hostname }}/amanuensis
    DB: postgresql://{{ .Files.Get "secrets/amanuensis-dbcreds/username" | default "" }}:{{ .Files.Get "secrets/amanuensis-dbcreds/password" | default "" }}@{{ .Files.Get "secrets/amanuensis-dbcreds/host" | default "" }}:5432/{{ .Files.Get "secrets/amanuensis-dbcreds/database" | default "" }}
    {{- with .Values.AMANUENSIS_CONFIG }}
    {{- toYaml . | nindent 4 }}
    {{ end }}