apiVersion: v1
kind: Service
metadata:
  name: "pcdcanalysistools-service"
  labels:
    {{- include "pcdcanalysistools.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pcdcanalysistools.selectorLabels" . | nindent 4 }}
