apiVersion: v1
kind: Secret
metadata:
  name: sheepdog-creds
type: Opaque
stringData:
  creds.json: |-
      {
        "db_host": "{{ include "gen3.service-postgres" (dict "key" "host" "service" $.Chart.Name "context" $) }}",
        "db_username": "{{include "gen3.service-postgres" (dict "key" "username" "service" $.Chart.Name "context" $) }}",
        "db_password": "{{include "gen3.service-postgres" (dict "key" "password" "service" $.Chart.Name "context" $) }}",
        "db_database": "{{ include "gen3.service-postgres" (dict "key" "database" "service" $.Chart.Name "context" $)}}",
        "hostname": "{{ .Values.global.hostname }}",
        "indexd_password": "",
        "fence_username": "{{include "gen3.service-postgres" (dict "key" "username" "service" "fence" "context" $) }}",
        "fence_password": "{{include "gen3.service-postgres" (dict "key" "password" "service" "fence" "context" $) }}",
        "fence_host": "{{ include "gen3.service-postgres" (dict "key" "host" "service" "fence" "context" $) }}",
        "fence_database": "{{ include "gen3.service-postgres" (dict "key" "database" "service" "fence" "context" $)}}"
      }
